#ifndef P3_WEAPON_SHARED_H
#define P3_WEAPON_SHARED_H

enum WeaponType_t
{
	WPN_TYPE_FLESH = -1,
	WPN_TYPE_NONE = 0,
	WPN_TYPE_ANIMAL,
	WPN_TYPE_GADGET,
	WPN_TYPE_NONLETHAL_MELEE,
	WPN_TYPE_NONLETHAL_RANGED,
	WPN_TYPE_MELEE,
	WPN_TYPE_RANGED,
	WPN_TYPE_BIGGUN,

	WPN_TYPE_SIZE,
};

WeaponType_t ParseWeaponType( const char *name );

enum WeaponID_t
{
	P3_WEAPON_WRONG = -1,
	P3_WEAPON_DISABLED = 0,
	P3_WEAPON_EMPTYHANDS = 1,
	P3_WEAPON_WOLVERINE,
	P3_WEAPON_NAILBAT,
	P3_WEAPON_GRENADE,
	P3_WEAPON_DESERT_EAGLE,
	P3_WEAPON_TASER,
	P3_WEAPON_SHOTGUN,
	P3_WEAPON_M60,
	P3_WEAPON_M16,
	P3_WEAPON_CAT,
	P3_WEAPON_MACHETE,
	P3_WEAPON_SHOVEL,
	P3_WEAPON_MOLOTOV,
	P3_WEAPON_GASOLINE,
	P3_WEAPON_CATNIP,
	P3_WEAPON_BANNER,
	P3_WEAPON_BEENEST,
	P3_WEAPON_COP_BATON,
	P3_WEAPON_KROTCHY_GRENADE,
	P3_WEAPON_HAMMER,
	P3_WEAPON_LASERPEN,
	P3_WEAPON_MATCH,
	P3_WEAPON_MAXEL_SNIPER,
	P3_WEAPON_METABULKY,
	P3_WEAPON_METAONEHANDLED,
	P3_WEAPON_METATWOHANDLED,
	P3_WEAPON_MONKEY,
	P3_WEAPON_PHOTOCAM,
	P3_WEAPON_SEED,
	P3_WEAPON_SHOPVAC,
	P3_WEAPON_SPRAY,
	P3_WEAPON_TVCAM,
	P3_WEAPON_WEEMOTE,
	P3_WEAPON_M136,
	P3_WEAPON_FIREAXE,
	P3_WEAPON_GAMAMET,
	P3_WEAPON_GLOCK17,
	P3_WEAPON_REVOLVER,
	P3_WEAPON_TTPISTOL,
	P3_WEAPON_AK47,
	P3_WEAPON_P90,
	P3_WEAPON_UZI,
	P3_WEAPON_COUNT,
// virtual weapons
	P3_WEAPON_DOG,
};

WeaponID_t ParseWeaponID( const char *sId );
const char* WeaponID2Name( WeaponID_t id );
/*
#define P3_WEAPON_EMPTYHANDS			1
#define P3_WEAPON_WOLVERINE				2
#define P3_WEAPON_NAILBAT				3
#define P3_WEAPON_GRENADE				4
#define P3_WEAPON_DESERT_EAGLE			5
#define P3_WEAPON_TASER					6
#define P3_WEAPON_SHOTGUN				7
#define P3_WEAPON_M60					8
#define P3_WEAPON_M16					9
#define P3_WEAPON_CAT					10
#define P3_WEAPON_MACHETE				11
#define P3_WEAPON_SHOVEL				12
#define P3_WEAPON_MOLOTOV				13
#define P3_WEAPON_GASOLINE				14
#define P3_WEAPON_CATNIP				15
#define P3_WEAPON_BANNER				16
#define P3_WEAPON_BEENEST				17
#define P3_WEAPON_COP_BATON				18
#define P3_WEAPON_KROTCHY_GRENADE		19
#define P3_WEAPON_HAMMER				20
#define P3_WEAPON_LASERPEN				21
#define P3_WEAPON_MATCH					22
#define P3_WEAPON_MAXEL_SNIPER			23
#define P3_WEAPON_METABULKY				24
#define P3_WEAPON_METAONEHANDLED		25
#define P3_WEAPON_METATWOHANDLED		26
#define P3_WEAPON_MONKEY				27
#define P3_WEAPON_PHOTOCAM				28
#define P3_WEAPON_SEED					29
#define P3_WEAPON_SHOPVAC				30
#define P3_WEAPON_SPRAY					31
#define P3_WEAPON_TVCAM					32
#define P3_WEAPON_WEEMOTE				33
#define P3_WEAPON_M136					34
*/
void P3_FillDmgInfo( const CTakeDamageInfo& info, class IGameEvent *event );


#endif // P3_WEAPON_SHARED_H
